apiVersion: v1
kind: Service
metadata:
  name: {{ include "lowcoder.fullname" . }}-api-service
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.service.type }}
  ports:
    - port: {{ .Values.apiService.service.port }}
      targetPort: lowcoder-api
      protocol: TCP
      name: lowcoder-api
    {{- if .Values.apiService.service.nodePort }}
      {{- if or (eq .Values.apiService.service.type "NodePort") (eq .Values.apiService.service.type "LoadBalancer") }}
      nodePort: {{ .Values.apiService.service.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "lowcoder.selectorLabels" . | nindent 4 }}
