auth:
  email:
    enable: true

spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: false
      uri: mongodb://localhost:27017/lowcoder?socketTimeoutMS=5000
  redis:
    url: redis://localhost:6379
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  http2:
    enabled: true
  port: 8080
  shutdown: graceful

default:
  orgs-per-user: 100
  org-member-count: 1000
  org-group-count: 100
  org-app-count: 1000
  developer-count: 50

common:
  cookie-name: LOCAL_LOWCODER_TOKEN
  product: lowcoder
  domain:
    default-value: skipCheck
  js-executor:
    host: ${LOWCODER_NODE_SERVICE_URL:http://127.0.0.1:6060}
  encrypt:
    password: lowcoder
    salt: lowcoder
  cloud: true
  security:
    cors-allowed-domains:
      - '*'
  version: 1.1.8
  block-hound-enable: false

material:
  mongodb-grid-fs:
    bucket-name: material

springdoc:
  api-docs:
    path: /api/docs/api-docs
  swagger-ui:
    path: /api/docs/swagger-ui
  paths-to-exclude: /api/v1/**
