spring:
  data:
    mongodb:
      authentication-database: admin
      uri: "mongodb://lowcoder:secret123@127.0.0.1:37017/lowcoder?authSource=admin"
    redis:
      url: "redis://127.0.0.1:16379"

server:
  port: 18080
common:
  cookie-name: LOWCODER_DEBUG_TOKEN
  js-executor:
    host: "http://127.0.0.1:16060"
  workspace:
    mode: SAAS

debug: true

logging:
  level:
    root: debug
    org.lowcoder: debug

