spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: false
      uri: mongodb://192.168.8.100:27017/lowcoder?authSource=admin
    redis:
      url: redis://192.168.8.100:6379
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  compression:
    enabled: true
  forward-headers-strategy: NATIVE
  http2:
    enabled: true
  port: 8080
  shutdown: graceful

default:
  orgs-per-user: 100
  org-member-count: 1000
  org-group-count: 100
  org-app-count: 1000
  developer-count: 50
  api-rate-limit: 50 

common:
  cookie-name: LOCAL_LOWCODER_TOKEN
  product: lowcoder
  domain:
    default-value: skipCheck
  encrypt:
    password: lowcoder
    salt: lowcoder
  cloud: true
  security:
    cors-allowed-domains:
      - '*'
  version: 1.1.8
  block-hound-enable: false
  js-executor:
    host: http://127.0.0.1:6060

material:
  mongodb-grid-fs:
    bucket-name: material

springdoc:
  api-docs:
    path: /api/docs/api-docs
  swagger-ui:
    path: /api/docs/swagger-ui
  paths-to-exclude: /api/v1/**

auth:
  api-key:
    secret: 123456789101112131415123456789101112131415123456789101112131415123456789101112131415
  email:
    enable: true
    enable-register: false