# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Lowcoder Comps

on:
  push:
    branches: [ "publish-comps-workflow" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #     - name: Install dependencies
  #       uses: borales/actions-yarn@v4.2.0
  #       with:
  #         cmd: install
  #         dir: client/packages/lowcoder-comps
  #     - name: Run tests
  #       uses: borales/actions-yarn@v4.2.0
  #       with:
  #         cmd: test
  #         dir: client/packages/lowcoder-comps

  publish-package:
    # needs: build
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #   # Setup .npmrc file to publish to npm
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: 16
    #       registry-url: https://registry.npmjs.org/
    #   # - run: cat .npmrc
    #   - run: echo ${{ secrets }}
    #   - name: Install dependencies
    #     uses: borales/actions-yarn@v4.2.0
    #     with:
    #       cmd: install
    #       dir: client/packages/lowcoder-comps
    #   - name: Publish
    #     uses: borales/actions-yarn@v4.2.0
    #     with:
    #       cmd: build_publish
    #       dir: client/packages/lowcoder-comps
    #     env:
    #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build ðŸ”§
        run: npm ci && npm run build
      - name: Publish package to NPM ðŸ“¦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}